#!/usr/bin/env python
### Generate markers
import cv2
import os

### --- parameter --- ###

# Save location
dir_mark = '/home/shubham/Shubham/Documents/aruco_markers'

# Parameter
num_mark = 4  # Number of markers
marker_size_cm = 23
dpi = 100
height_cm = 10
width_cm = 15
pixel_size = int(marker_size_cm * dpi / 2.54)
new_height = int(height_cm * dpi / 2.54)
new_width = int(width_cm * dpi / 2.54)

# Define the ArUco dictionary
dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_6X6_250)

for count in range(num_mark):
    id_mark = count
    img_mark = cv2.aruco.generateImageMarker(dictionary, id_mark, pixel_size)
    #resized_marker = cv2.resize(img_mark, (new_width, new_height))

    if count < 10:
        img_name_mark = 'mark_id_0' + str(count) + '.jpg'
    else:
        img_name_mark = 'mark_id_' + str(count) + '.jpg'
    path_mark = os.path.join(dir_mark, img_name_mark)

    cv2.imwrite(path_mark, img_mark)
